[build]
  command = ""
  publish = "public"



[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Origin-Credentials= "true"
Access-Control-Allow-Headers = "Content-Type"
Access-Control-Allow-Methods = "GET,POST,PUT,DELETE,OPTION"
